include:
  - electronic_hw_design_lab.md
  - digital_systems_design.md
  - microprocessors.md
  - embedded_systems_design.md
  - hd.md
  - mp2022-1.md
  - esd2022-1.md
  
locale: "ko-KR"
name: something
title: null
